use_frameworks!

platform :ios, '8.0'

target 'UnReadBubbleView_Example' do
  pod 'UnReadBubbleView', :path => '../'

  target 'UnReadBubbleView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
